# Generated by Django 4.0.2 on 2022-05-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ovccaretransfer',
            name='transfering_org',
        ),
    ]
