# Generated by Django 4.0.4 on 2022-05-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0002_alter_ovccaretransfer_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovccaretransfer',
            name='reason',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
