# Generated by Django 4.0.2 on 2022-05-07 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '0001_initial'),
        ('cpovc_forms', '0003_remove_ovccaretransfer_transfering_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovccaretransfer',
            name='organization_from',
            field=models.ForeignKey(default=56, on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regorgunit'),
        ),
    ]
