# Generated by Django 4.0.4 on 2022-04-25 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0003_alter_ovchivmanagement_substitution_firstline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovchivmanagement',
            name='substitution_firstline_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 14, 49, 34, 117344)),
        ),
    ]
