# Generated by Django 4.0.4 on 2022-05-01 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0003_alter_ovccaretransfer_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovccaretransfer',
            name='event',
            field=models.ForeignKey(default='b7ea884e-c933-11ec-89a4-e1fe85340968', on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccareevents'),
        ),
    ]
