# Generated by Django 4.0.2 on 2022-05-07 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '0001_initial'),
        ('cpovc_forms', '0004_ovccaretransfer_organization_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovccaretransfer',
            name='organization_from',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regorgunit'),
        ),
    ]
