# Generated by Django 4.0.2 on 2022-05-07 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0006_alter_ovccaretransfer_organization_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ovccaretransfer',
            old_name='organization_from',
            new_name='organization_to',
        ),
    ]
