# Generated by Django 4.0.2 on 2022-05-07 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '0001_initial'),
        ('cpovc_forms', '0007_rename_organization_from_ovccaretransfer_organization_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ovccaretransfer',
            name='organization_to',
        ),
        migrations.AddField(
            model_name='ovccaretransfer',
            name='organization_from',
            field=models.ForeignKey(default=56, on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regorgunit'),
        ),
    ]
